version: '2'
services:
    shop-app:
        image: shop
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shop-postgresql:5432/shop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shop-postgresql:
        extends:
            file: postgresql.yml
            service: shop-postgresql
